### ISSUE TITLE
Export failure

### ISSUE THREAD

**Issue by squromiv** [dbeley/youtube_extract#12]
Channel: https://www.youtube.com/channel/UC5hcH25pD-rgIlQvzErgE7A

![screen_2020 08 08 001](https://user-images.githubusercontent.com/15985877/89704937-7f5bd000-d961-11ea-91fc-76bbdcb6037b.png)

**Comment by dbeley** [comment]
Hello,

Thanks for the issue, the dependencies were outdated, it should be working fine now. Can you update `youtube_extract` and try again (`pip install youtube_extract --upgrade`)?

I've managed to run the script with the channel you provided, it took ~1100 seconds on my end. I've joined the xlsx output for the channel you provided in case you don't manage to run it.

Cheers!

[youtube_extract_oblomoff.xlsx](https://github.com/dbeley/youtube_extract/files/5045146/youtube_extract_oblomoff.xlsx)
