### ISSUE TITLE
Connection is forcibly closed by a remote host

### ISSUE THREAD

**Issue by squromiv** [dbeley/youtube_extract#2]
Hi! I`ve liked this tool, but I have some problem with channels, which contain many videos. After processing of about 500 videos, I get the next message.
![screen_2020 03 23 001](https://user-images.githubusercontent.com/15985877/77358710-627c8280-6d5b-11ea-8735-d698683a291a.png)

**Comment by dbeley** [comment]
Hello it seems to be a problem with youtube-dl, which is used by youtube_extract.

I've updated the dependencies of youtube_extract, hopefully it will fix your problem. 

Can you update youtube_extract (`pip install youtube_extract --upgrade`) and try again the extaction?

**Comment by squromiv** [comment]
Thank you. It looks like OK now. 
But I have another trouble with videos, which titles contain сyrillic symbols. They are unreadable in csv. I have zero knowledge about programming. In the file "__main__.py" I changed the string 

`encoding="utf-8"
to 
`encoding="cp1251"
But have bad result.
Can you improve youtube_extract in the right way?

![screen_2020 03 24 001](https://user-images.githubusercontent.com/15985877/77470573-f022a580-6e21-11ea-968b-0483458f25a9.png)

**Comment by dbeley** [comment]
Hi I've tried with this russian channel : https://www.youtube.com/user/RedCynicRus/videos (~120 seconds to complete) and the extraction works great and the cyrillic symbols are correctly read (I use libreoffice to import the csv file) : 
![Capture d’écran du 2020-03-24 22-02-23](https://user-images.githubusercontent.com/6568955/77476645-d88ff080-6e12-11ea-89e0-315f3cfccf12.png)

I think it might be an issue with the software you use to import the file which I assume is Microsoft Excel. Can you try with libreoffice (it's free alternative to excel)? I'm aware it's not a perfect solution, I'm gonna try to add an .xlsx export which hopefull will solve the problem.

**Comment by dbeley** [comment]
I've uploaded a new version where you can use the `-e` flag to set the export format (csv or xlsx).

Can you try updating `youtube_extract` and try an export with xlsx as export format ? Thanks in advance.

Example :
`youtube_extract -e xlsx https://www.youtube.com/user/RedCynicRus/videos`

**Comment by squromiv** [comment]
Thanks. Your method works good for observing. XLSX looks as useful option.

But in order to process data, I need to use software, that support import of only CSV-files in Unicode or ANSI encoding. So the solution of my problem: to open CSV in UTF-8 and re-save it in Unicode encoding. 

Nevertheless, thank you so much for such a handy tool and quick reply.
